/**
 * compliance-demo.mjs — the artifact for a buyer who has to approve, not integrate.
 *
 *   node demo-qa/compliance-demo.mjs
 *   → writes compliance-evidence.html (self-contained, print to PDF, forwardable)
 *
 * The pitch for a regulated buyer is not a feature list, it is a question their data
 * protection officer has to answer: "when this tool reads a page containing personal
 * data, what reaches the model, and can we prove it?" A screen recording cannot answer
 * that. A side-by-side of the same page read with and without a policy, plus the
 * attestation and the audit line, can.
 *
 * Everything here is generated by actually running the tool against a local fixture with
 * SYNTHETIC data. No real personal data, no network, no model.
 */
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { spawn } from 'node:child_process'
import { writeFile, readFile, readdir } from 'node:fs/promises'
import { createServer } from 'node:http'
import { daemonFetch } from '../tools/daemon-client.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const AGENT = join(HERE, '..')
const BROWSE = join(AGENT, 'tools/browse.mjs')
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// Obviously-synthetic record. The point is the mechanism, not the data.
const CASE = { name: 'Marta Quiroga', email: 'm.quiroga@example-clinic.test', phone: '+54 11 5555 0142', ref: 'CASE-88213' }
const PAGE = `<!doctype html><html><head><title>Patient record ${CASE.ref}</title></head><body>
<h1>Patient record</h1>
<dl>
  <dt>Name</dt><dd>${CASE.name}</dd>
  <dt>Contact</dt><dd><a href="mailto:${CASE.email}">${CASE.email}</a></dd>
  <dt>Phone</dt><dd><a href="tel:${CASE.phone.replace(/\s/g, '')}">${CASE.phone}</a></dd>
  <dt>Reference</dt><dd>${CASE.ref}</dd>
</dl>
<a href="/records/${CASE.ref}/notes">Clinical notes</a>
<p>Appointment confirmed for next Tuesday. No outstanding balance.</p>
</body></html>`

const PORT = 8407
const srv = createServer((req, res) => {
  res.writeHead(200, { 'content-type': 'text/html' })
  res.end(PAGE)
})
await new Promise((r) => srv.listen(PORT, '127.0.0.1', r))
const URL_ = `http://127.0.0.1:${PORT}/records/${CASE.ref}`

const daemon = spawn(process.execPath, [BROWSE, 'serve'], { stdio: 'ignore' })
const cmd = (c, args = []) => daemonFetch({
  method: 'POST', headers: { 'content-type': 'application/json' },
  body: JSON.stringify({ cmd: c, args, envelope: true }),
}).then((r) => r.json()).catch((e) => ({ ok: false, error: String(e) }))
for (let i = 0; i < 40; i++) { const r = await cmd('status'); if (r.ok) break; await sleep(500) }

// ── 1 · no policy: what an ordinary reading sends to the model ───────────────────────
const before = await cmd('open', [URL_])

// ── 2 · with a policy: the same page, the same instant, the same call ────────────────
const RULES = [CASE.name, CASE.email, CASE.phone, CASE.ref]
const after = await cmd('open', [URL_, '--redact-json', JSON.stringify(RULES)])

// ── 3 · can the hidden value be probed for? ──────────────────────────────────────────
const probe = await cmd('assert', [JSON.stringify({ exists: CASE.name })])

// ── 4 · what the operator's audit log recorded ───────────────────────────────────────
const logDir = join(AGENT, 'logs')
let logLine = '(no log line captured)'
try {
  const files = (await readdir(logDir)).filter((f) => f.endsWith('.jsonl')).sort()
  const lines = (await readFile(join(logDir, files[files.length - 1]), 'utf8')).trim().split('\n')
  logLine = lines.reverse().find((l) => l.includes('"cmd":"open"')) || logLine
} catch { /* keep the placeholder */ }
await cmd('redact', ['off'])

// ── Evidence ─────────────────────────────────────────────────────────────────────────
const leaked = (o) => RULES.filter((t) => JSON.stringify(o).toLowerCase().includes(t.toLowerCase()))
const beforeLeaks = leaked(before)
const afterLeaks = leaked(after)
const esc = (x) => String(x).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]))
const pretty = (o) => esc(JSON.stringify(o, null, 1))

const html = `<!doctype html><meta charset="utf-8"><title>Observation-boundary redaction — evidence</title>
<style>
 :root{--ink:#111;--mut:#666;--line:#ddd;--bad:#b00020;--good:#0a6b3d;--bg:#fafafa}
 body{font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:var(--ink);max-width:52rem;margin:3rem auto;padding:0 1.5rem}
 h1{font-size:1.6rem;margin:0 0 .2rem} h2{font-size:1.05rem;margin:2.2rem 0 .6rem;padding-top:.9rem;border-top:1px solid var(--line)}
 .sub{color:var(--mut);margin:0 0 2rem}
 pre{background:var(--bg);border:1px solid var(--line);border-radius:6px;padding:.7rem .9rem;overflow-x:auto;font-size:12.5px;line-height:1.45}
 .bad{color:var(--bad);font-weight:600}.good{color:var(--good);font-weight:600}
 table{border-collapse:collapse;width:100%;margin:.5rem 0}td,th{border-bottom:1px solid var(--line);padding:.45rem .6rem;text-align:left;vertical-align:top}
 th{font-weight:600;color:var(--mut);font-size:.85rem;text-transform:uppercase;letter-spacing:.03em}
 .note{background:#fff8e6;border:1px solid #f0dca0;border-radius:6px;padding:.7rem .9rem;margin:1rem 0}
 footer{margin-top:3rem;color:var(--mut);font-size:.85rem;border-top:1px solid var(--line);padding-top:1rem}
</style>
<h1>Observation-boundary redaction</h1>
<p class="sub">Evidence pack · generated ${new Date().toISOString().slice(0, 10)} · synthetic record, no real personal data</p>

<h2>The question this answers</h2>
<p>When an automated agent reads a page containing personal data, <strong>what reaches the language model</strong>, and can it be proven afterwards? Filtering the model's output does not answer it: by then the data has already entered the model's context and the transcript. This tool applies the policy <em>before</em> the observation leaves the page.</p>

<h2>The page being read</h2>
<pre>${esc(PAGE.trim())}</pre>

<h2>1 · Read with no policy — what would reach the model</h2>
<p>Terms found in the payload: <span class="bad">${beforeLeaks.length} of ${RULES.length}</span> ${beforeLeaks.map((t) => `<code>${esc(t)}</code>`).join(', ')}</p>
<pre>${pretty(before.meta?.digest?.top || [])}</pre>

<h2>2 · The same page, same call, with a policy</h2>
<p>Terms found in the payload: <span class="${afterLeaks.length ? 'bad' : 'good'}">${afterLeaks.length} of ${RULES.length}</span>${afterLeaks.length ? ' ' + afterLeaks.map((t) => `<code>${esc(t)}</code>`).join(', ') : ' — none'}</p>
<pre>${pretty(after.meta?.digest?.top || [])}</pre>
<table>
 <tr><th>Property</th><th>Result</th></tr>
 <tr><td>Page URL as reported</td><td><code>${esc(after.url)}</code></td></tr>
 <tr><td>Values inside <code>href</code> attributes</td><td>${after.meta?.digest?.top?.some((e) => e.href && RULES.some((t) => String(e.href).toLowerCase().includes(t.toLowerCase()))) ? '<span class="bad">present</span>' : '<span class="good">covered by the policy</span>'}</td></tr>
 <tr><td>Attestation returned with the observation</td><td><code>${esc(JSON.stringify(after.meta?.privacy || null))}</code></td></tr>
 <tr><td>Form input values</td><td>never serialised — masked and hashed by design, policy or not</td></tr>
</table>

<h2>3 · Can the hidden value be probed for?</h2>
<p>A caller asks whether the redacted name is present. Answering — even "no" — would confirm or deny it, one bit at a time. The request is refused instead:</p>
<pre>${esc((probe.text || '').split('\n').slice(0, 3).join('\n'))}</pre>

<h2>4 · What the operator's audit log recorded</h2>
<pre>${esc(logLine.length > 700 ? logLine.slice(0, 700) + ' …' : logLine)}</pre>
<p>The log records that a policy was active and how many rules it had — never the rule text, because the terms are the very strings the operator asked to hide.</p>

<h2>Limits — stated before purchase, not after</h2>
<div class="note">
<ul>
<li><strong>This protects against the consumer</strong> (the model, the transcript, the logs). It is not a defence against code running inside the page, which by definition already has the DOM.</li>
<li><strong>Screenshots are pixels and are not redacted.</strong> If a region is sensitive, do not request its image.</li>
<li><strong>Matching is literal substring, case-insensitive.</strong> It does not infer that "M. Quiroga" is the same person as "Marta Quiroga"; rules are supplied by the operator.</li>
<li><strong>Saved reference points contain a non-salted hash of input values.</strong> A holder could test a <em>guessed</em> value against one. Treat them as sensitive artifacts.</li>
<li><strong>Authenticated pages:</strong> this tool uses an isolated browser context. It reports <code>authState: unknown</code> and the cookie count instead of inferring identity from cookies alone.</li>
</ul>
</div>

<footer>
Reproduce: <code>node demo-qa/compliance-demo.mjs</code>.
The behaviour shown is covered by automated gates — <code>npm run test:contract</code>
(15 checks, including that redaction covers <code>href</code> and that a probe is refused)
and 8 unit tests in <code>test/privacy-probe.test.js</code>.
</footer>`

const out = join(HERE, 'compliance-evidence.html')
await writeFile(out, html)

await new Promise((r) => { const s = spawn(process.execPath, [BROWSE, 'stop'], { stdio: 'ignore' }); s.on('exit', r) })
try { daemon.kill() } catch { /* gone */ }
srv.close(); srv.closeAllConnections?.()

console.log(`no policy  → ${beforeLeaks.length}/${RULES.length} terms in the payload`)
console.log(`with policy → ${afterLeaks.length}/${RULES.length} terms in the payload`)
console.log(`probe refused: ${/blocked by privacy rule/.test(probe.text || '')}`)
console.log(`\n→ ${out}`)
process.exit(afterLeaks.length === 0 && beforeLeaks.length > 0 ? 0 : 1)
